routes/admin.php
<?php

/*
  |--------------------------------------------------------------------------
  | Admin Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register Admin routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::group(['namespace' => 'Auth', 'as' => 'admin.'], function () {
    Route::get('/login', 'AdminLoginController@showLoginForm')->name('login');
    Route::post('/login', 'AdminLoginController@login')->name('login.submit');
    Route::post('/logout', 'AdminLoginController@logout')->name('logout');

    //admin password reset routes
    Route::post('/password/email', 'AdminForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/password/reset', 'AdminForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/password/reset', 'AdminResetPasswordController@reset');
    Route::get('/password/reset/{token}', 'AdminResetPasswordController@showResetForm')->name('password.reset');
});

Route::group(['middleware' => 'isAdmin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {
    Route::get('/', 'HomeController@index')->name('dashboard');
    Route::resource('users', 'AdminController');
    Route::any('users/dt', 'AdminController@datatable')->name('users.datatable');
    Route::get('user/profile', 'AdminController@profile')->name('user.profile');
    Route::post('user/profile', 'AdminController@profilePost')->name('user.profile.post');
    Route::post('user/profile/avatardelete', 'AdminController@avatarDelete')->name('user.avatardelete');

    Route::resource('roles', 'RoleController');
    Route::resource('permissions', 'PermissionController');
});

routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::group(['middleware' => ['web']], function () {

    Route::get('/', 'Web\HomeController@index')->name('home');

// Login Routes...
    Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
    Route::post('login', ['as' => 'login.post', 'uses' => 'Auth\LoginController@login']);
    Route::post('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);

    // Registration Routes...
    Route::get('register', ['as' => 'register', 'uses' => 'Auth\RegisterController@showRegistrationForm']);
    Route::post('register', ['as' => 'register.post', 'uses' => 'Auth\RegisterController@register']);

    // Password Reset Routes...
    Route::get('password/request', ['as' => 'password.request', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
    Route::post('password/email', ['as' => 'password.email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
    Route::get('password/reset/{token}', ['as' => 'password.reset', 'uses' => 'Auth\ResetPasswordController@showResetForm']);
    Route::post('password/reset', ['as' => 'password.reset.post', 'uses' => 'Auth\ResetPasswordController@reset']);
});

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Auth;
//Importing laravel-permission models
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use Session;

class RoleController extends Controller {

    public function __construct() {
        $this->middleware(function ($request, $next) {
            $user = Auth::guard('admin')->user();
            if ($user->hasRole('super-admin', 'admin') || $user->hasPermissionTo('role_read', 'admin')) {
                return $next($request);
            } else {
                return redirect()->route('admin.dashboard')
                                ->with('growl', ['Your don\'t have permission to acces this page.', 'danger']);
            }
        });

        $this->middleware(function ($request, $next) {
            $user = Auth::guard('admin')->user();
            if ($user->hasRole('super-admin', 'admin') || $user->hasPermissionTo('role_create', 'admin')) {
                return $next($request);
            } else {
                return redirect()->route('admin.dashboard')
                                ->with('growl', ['Your don\'t have permission to acces this page.', 'danger']);
            }
        }, ['only' => ['create', 'store']]);

        $this->middleware(function ($request, $next) {
            $user = Auth::guard('admin')->user();
            if ($user->hasRole('super-admin', 'admin') || $user->hasPermissionTo('role_update', 'admin')) {
                return $next($request);
            } else {
                return redirect()->route('admin.dashboard')
                                ->with('growl', ['Your don\'t have permission to acces this page.', 'danger']);
            }
        }, ['only' => ['edit', 'update']]);

        $this->middleware(function ($request, $next) {
            $user = Auth::guard('admin')->user();
            if ($user->hasRole('super-admin', 'admin') || $user->hasPermissionTo('role_delete', 'admin')) {
                return $next($request);
            } else {
                return redirect()->route('admin.dashboard')
                                ->with('growl', ['Your don\'t have permission to acces this page.', 'danger']);
            }
        }, ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $roles = Role::where('id', '!=', 1)->where('guard_name', '=', 'admin')->get(); //Get all roles

        return view('admin.roles.index')->with('roles', $roles);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $permissions = Permission::where('guard_name', '=', 'admin')->orderBy('id', 'asc')->pluck('id', 'name')->toArray(); //Get all permissions
        $target = [];
        foreach ($permissions as $k => $v) {
            $keys = explode("_", $k);
            if (count($keys) > 1) {
                $target[$keys[0]][$v] = $keys[1];
            } else {
                $target[$k] = $v;
            }
        }
        return view('admin.roles.create', ['permissions' => $target]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        //Validate name and permissions field
        $this->validate($request, [
            'name' => 'required|unique:roles|max:10',
            'permissions' => 'required',
                ]
        );

        $name = $request['name'];
        $role = new Role();
        $role->name = $name;
        $role->guard_name = 'admin';

        $permissions = $request['permissions'];

        $role->save();
        //Looping thru selected permissions
        foreach ($permissions as $permission) {
            $p = Permission::where('id', '=', $permission)->firstOrFail();
            //Fetch the newly created role and assign permission
            $role = Role::where('name', '=', $name)->first();
            $role->givePermissionTo($p);
        }

        return redirect()->route('admin.roles.index')
                        ->with('growl', ['Role ' . $role->name . ' added!', 'success']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        return redirect('roles');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $role = Role::findOrFail($id);

        $permissions = Permission::orderBy('id', 'asc')->where('guard_name', '=', 'admin')->pluck('id', 'name')->toArray(); //Get all permissions
        $target = [];
        foreach ($permissions as $k => $v) {
            $keys = explode("_", $k);
            if (count($keys) > 1) {
                $target[$keys[0]][$v] = $keys[1];
            } else {
                $target[$k] = $v;
            }
        }

        $permissions = $target;
        return view('admin.roles.edit', compact('role', 'permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {

        $role = Role::findOrFail($id); //Get role with the given id
        //Validate name and permission fields
        $this->validate($request, [
            'name' => 'required|max:10|unique:roles,name,' . $id,
            'permissions' => 'required',
        ]);

        $input = $request->except(['permissions']);
        $permissions = $request['permissions'];
        $role->fill($input)->save();

        $p_all = Permission::all(); //Get all permissions

        foreach ($p_all as $p) {
            $role->revokePermissionTo($p); //Remove all permissions associated with role
        }

        foreach ($permissions as $permission) {
            $p = Permission::where('id', '=', $permission)->firstOrFail(); //Get corresponding form //permission in db
            $role->givePermissionTo($p);  //Assign permission to role
        }

        return redirect()->route('admin.roles.index')
                        ->with('growl', ['Role ' . $role->name . ' updated!', 'success']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        $role = Role::findOrFail($id);
        if ($role->id == 1 || $role->id == 2) {
            return redirect()->route('admin.roles.index')
                            ->with('growl', ['Cannot delete this Role!', 'danger']);
        }
        $role->delete();

        return redirect()->route('admin.roles.index')
                        ->with('growl', ['Role deleted!', 'success']);
    }

}

resources/views/admin/roles/create.blade.php
@extends('adminlte::page')

@section('title', 'Add New Role')

@section('content_header')
<h1><i class='fa fa-key'></i> Add Role</h1>
@stop

@section('content')
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="box box-danger">
            <div class="x_panel">
                <div class="x_content">

                    {{ Form::open(array('url' => 'admin/roles')) }}
                    <div class="box-body">
                        <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                            {{ Form::label('name', 'Name') }}
                            {{ Form::text('name', null, array('class' => 'form-control')) }}
                             {!! $errors->first('name','<p class="text-danger"><strong>:message</strong></p>') !!}
                        </div>

                        <div class="panel panel-default ">

                            <div class="panel-heading"><h5><b>Assign Permissions</b></h5></div>

                            <div class="panel-body">
                                @foreach ($permissions as $k => $v)
                                @if(is_array($v))
                                <div class="panel panel-default" style="clear: both;">
                                    <div class="panel-body">
                                        <div class="panel-heading"><b>{{ucfirst($k)}}</b></div>
                                        @foreach ($v as $k1 => $v1)
                                        <div class="col-md-3">
                                            {{ Form::checkbox('permissions[]',  $k1,  null, ['class'=>'checkboxRole minimal-red'] ) }}
                                            {{ Form::label($v1, ucfirst($v1)) }}
                                        </div>
                                        @endforeach
                                    </div>
                                </div>
                                @else
                                <div class="col-md-3">
                                    {{ Form::checkbox('permissions[]',  $v,  null, ['class'=>'checkboxRole minimal-red'] ) }}
                                    {{ Form::label($k, ucfirst($k)) }}
                                </div>
                                @endif
                                @endforeach
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                {{ Form::submit('Add', array('class' => 'btn btn-primary')) }}
                            </div>
                        </div>
                    </div>
                    {{ Form::close() }}

                </div>
            </div>
        </div>
    </div>
</div>
@stop
@section('css')
<link rel="stylesheet" href="{{asset('vendor/adminlte/plugins/iCheck/all.css')}}">
@stop
@section('js')
<script src="{{asset('vendor/adminlte/plugins/iCheck/icheck.min.js')}}"></script>
<script type='text/javascript'>
$(function () {
    //Red color scheme for iCheck
    $('input[type="checkbox"].minimal-red, input[type="radio"].minimal-red').iCheck({
        checkboxClass: 'icheckbox_minimal-red',
        radioClass: 'iradio_minimal-red'
    })
});
</script>    
@stop

resources/views/admin/roles/edit.blade.php
@extends('adminlte::page')

@section('title', 'Edit Role')

@section('content_header')
<h1><i class='fa fa-key'></i> Edit Role: {{$role->name}}</h1>
@stop

@section('content')
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="box box-danger">
            <div class="x_panel">
                <div class="x_content">

                    {{ Form::model($role, array('route' => array('admin.roles.update', $role->id), 'method' => 'PUT')) }}
                    <div class="box-body">
                         <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                            {{ Form::label('name', 'Role Name') }}
                            {{ Form::text('name', null, array('class' => 'form-control')) }}
                             {!! $errors->first('name','<p class="text-danger"><strong>:message</strong></p>') !!}
                        </div>

                        <div class="panel panel-default ">

                            <div class="panel-heading"><h5><b>Assign Permissions</b></h5></div>

                            <div class="panel-body">

                                @foreach ($permissions as $k => $v)
                                @if(is_array($v))
                                <div class="panel panel-default" style="clear: both;">
                                    <div class="panel-body">
                                        <div class="panel-heading"><b>{{ucfirst($k)}}</b></div>
                                        @foreach ($v as $k1 => $v1)
                                        <div class="col-md-3">
                                            {{ Form::checkbox('permissions[]',  $k1,  $role->permissions, ['class'=>'checkboxRole minimal-red'] ) }}
                                            {{ Form::label($v1, ucfirst($v1)) }}
                                        </div>
                                        @endforeach
                                    </div>
                                </div>
                                @else
                                <div class="col-md-3">
                                    {{ Form::checkbox('permissions[]',  $v,  $role->permissions, ['class'=>'checkboxRole minimal-red'] ) }}
                                    {{ Form::label($k, ucfirst($k)) }}
                                </div>
                                @endif
                                @endforeach
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                {{ Form::submit('Update', array('class' => 'btn btn-primary')) }}
                            </div>
                        </div>
                    </div>
                    {{ Form::close() }}    
                </div>
            </div>
        </div>
    </div>
</div>

@stop
@section('css')
<link rel="stylesheet" href="{{asset('vendor/adminlte/plugins/iCheck/all.css')}}">
@stop
@section('js')
<script src="{{asset('vendor/adminlte/plugins/iCheck/icheck.min.js')}}"></script>
<script type='text/javascript'>
$(function () {
    //Red color scheme for iCheck
    $('input[type="checkbox"].minimal-red, input[type="radio"].minimal-red').iCheck({
        checkboxClass: 'icheckbox_minimal-red',
        radioClass: 'iradio_minimal-red'
    })
});
</script>    
@stop

resources/views/admin/roles/index.blade.php
@extends('adminlte::page')

@section('title', 'Roles')

@section('content_header')
<h1><i class="fa fa-key"></i> Roles
    @stop

    @section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="box box-success">
                <div class="box-header">
                    <?php $user = Auth::guard('admin')->user(); ?>
                    @if($user->hasRole('super-admin','admin') || $user->hasPermissionTo('user_read','admin'))
                    <a href="{{ route('admin.users.index') }}" class="btn btn-default pull-right btn-sm">Users</a>
                    @endif
                    @if($user->hasRole('super-admin','admin') || $user->hasPermissionTo('permission_read','admin'))
                    <a href="{{ route('admin.permissions.index') }}" class="btn btn-default pull-right btn-sm">Permissions</a>
                    @endif
                    @if($user->hasRole('super-admin','admin') || $user->hasPermissionTo('role_create','admin'))
                    <a href="{{ URL::to('admin/roles/create') }}" class="btn btn-success pull-right btn-sm">Add Role</a>
                    @endif
                </div>
                <div class="box-body">

                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover" id="role-table">
                            <thead>
                                <tr>
                                    <th>Role</th>
                                    <th>Permissions</th>
                                    <th>Operation</th>
                                </tr>
                            </thead>

                            <tbody>
                                @foreach ($roles as $role)
                                <tr>

                                    <td>{{ $role->name }}</td>

                                    <td style="width: 70%;">
                                        {!! '<span class="label label-outlined">'.implode('</span> <span class="label label-outlined">', $role->permissions()->pluck('name')->toArray()).'</span>' !!}
                                    </td>
                                    <td style="width: 10%;">
                                        @if($user->hasRole('super-admin','admin') || $user->hasPermissionTo('role_update','admin'))
                                        <a href="{{ URL::to('admin/roles/'.$role->id.'/edit') }}" class="btn btn-xs btn-info pull-left" style="margin-right: 3px;">Edit</a>
                                        @endif
                                        @if($user->hasRole('super-admin','admin') || $user->hasPermissionTo('role_delete','admin'))
                                        {!! Form::open(['method' => 'DELETE', 'route' => ['admin.roles.destroy', $role->id] ]) !!}
                                        {!! Form::submit('Delete', ['class' => 'btn btn-xs btn-danger destroy']) !!}
                                        {!! Form::close() !!}
                                        @endif
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>

                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
    @stop
    @section('js')
    <script type='text/javascript'>
        $(function () {
            $('#role-table').on('click', '.destroy', function (e) {
                e.preventDefault();
                var form = $(this);
                bootbox.confirm("{{ trans('myadmin.confirm-delete') }}", function (result) {
                    if (result === false) {
                        return;
                    } else {
                        form.parent().submit();
                    }
                });
            });
        });
    </script>    
    @stop