routes/admin.php
<?php

/*
  |--------------------------------------------------------------------------
  | Admin Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register Admin routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::group(['namespace' => 'Auth', 'as' => 'admin.'], function () {
    Route::get('/login', 'AdminLoginController@showLoginForm')->name('login');
    Route::post('/login', 'AdminLoginController@login')->name('login.submit');
    Route::post('/logout', 'AdminLoginController@logout')->name('logout');

    //admin password reset routes
    Route::post('/password/email', 'AdminForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/password/reset', 'AdminForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/password/reset', 'AdminResetPasswordController@reset');
    Route::get('/password/reset/{token}', 'AdminResetPasswordController@showResetForm')->name('password.reset');
});

Route::group(['middleware' => 'isAdmin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {
    Route::get('/', 'HomeController@index')->name('dashboard');
    Route::resource('users', 'AdminController');
    Route::any('users/dt', 'AdminController@datatable')->name('users.datatable');
    Route::get('user/profile', 'AdminController@profile')->name('user.profile');
    Route::post('user/profile', 'AdminController@profilePost')->name('user.profile.post');
    Route::post('user/profile/avatardelete', 'AdminController@avatarDelete')->name('user.avatardelete');

    Route::resource('roles', 'RoleController');
    Route::resource('permissions', 'PermissionController');
});

routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::group(['middleware' => ['web']], function () {

    Route::get('/', 'Web\HomeController@index')->name('home');

// Login Routes...
    Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
    Route::post('login', ['as' => 'login.post', 'uses' => 'Auth\LoginController@login']);
    Route::post('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);

    // Registration Routes...
    Route::get('register', ['as' => 'register', 'uses' => 'Auth\RegisterController@showRegistrationForm']);
    Route::post('register', ['as' => 'register.post', 'uses' => 'Auth\RegisterController@register']);

    // Password Reset Routes...
    Route::get('password/request', ['as' => 'password.request', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
    Route::post('password/email', ['as' => 'password.email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
    Route::get('password/reset/{token}', ['as' => 'password.reset', 'uses' => 'Auth\ResetPasswordController@showResetForm']);
    Route::post('password/reset', ['as' => 'password.reset.post', 'uses' => 'Auth\ResetPasswordController@reset']);
});

app/Admin.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;
use App\Notifications\AdminResetPasswordNotification;
use Illuminate\Database\Eloquent\SoftDeletes;

class Admin extends Authenticatable {

    use Notifiable;
    use HasRoles;
    use SoftDeletes;

    protected $guard = 'admin';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'admin_id', 'name', 'email', 'password', 'status', 'type', 'last_login'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function setPasswordAttribute($password) {
        $this->attributes['password'] = bcrypt($password);
    }

    /**
     * Check if current user has an avatar
     *
     * @return string|false
     */
    public function getAvatarPathAttribute() {
        return public_path('images/avatars/' . md5($this->id . $this->created_at) . '.jpg');
    }

    /**
     * Return current user avatar uri
     *
     * @return string
     */
    public function getAvatarUrlAttribute() {
        if (is_file($this->avatar_path)) {
            $ts = filemtime($this->avatar_path);
            return asset('images/avatars/' . md5($this->id . $this->created_at) . '.jpg?t=' . $ts);
        }
        return asset("/images/default_user.png");
    }

    public function sendPasswordResetNotification($token) {
        $this->notify(new AdminResetPasswordNotification($token));
    }

}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use Uuids;
    use Notifiable;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

resources/views/admin/users/create.blade.php
@extends('adminlte::page')

@section('title', 'Add new Admin User')

@section('content_header')
<h1><i class='fa fa-user-plus'></i> Add User</h1>
@stop

@section('content')
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="box box-primary">
            <div class="box-header with-border">
                <a href="{{ url('/admin/users') }}" title="Back"><button class="btn btn-warning btn-xs"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
            </div>
            <div class="box-body">

                {{ Form::open(array('url' => 'admin/users')) }}

                <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                    {{ Form::label('name', 'Name') }}
                    {{ Form::text('name', '', array('class' => 'form-control')) }}
                    {!! $errors->first('name','<p class="text-danger"><strong>:message</strong></p>') !!}
                </div>

                <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                    {{ Form::label('email', 'Email') }}
                    {{ Form::email('email', '', array('class' => 'form-control')) }}
                    {!! $errors->first('email','<p class="text-danger"><strong>:message</strong></p>') !!}
                </div>

                <div class='form-group'>
                    @foreach ($roles as $role)
                    {{ Form::checkbox('roles[]',  $role->id ) }}
                    {{ Form::label($role->name, ucfirst($role->name)) }}<br>

                    @endforeach
                </div>

                <div class="form-group {{ $errors->has('password') ? 'has-error' : '' }}">
                    {{ Form::label('password', 'Password') }}<br>
                    {{ Form::password('password', array('class' => 'form-control')) }}
                    {!! $errors->first('password','<p class="text-danger"><strong>:message</strong></p>') !!}
                </div>

                <div class="form-group {{ $errors->has('password_confirmation') ? 'has-error' : '' }}">
                    {{ Form::label('password', 'Confirm Password') }}<br>
                    {{ Form::password('password_confirmation', array('class' => 'form-control')) }}
                    {!! $errors->first('password_confirmation','<p class="text-danger"><strong>:message</strong></p>') !!}
                </div>

                {{ Form::submit('Add', array('class' => 'btn btn-primary')) }}

                {{ Form::close() }}

            </div>
        </div>
    </div>
</div>
@stop

resources/views/admin/users/edit.blade.php
@extends('adminlte::page')

@section('title', 'Edit Admin User')

@section('content_header')
<h1><i class='fa fa-user-plus'></i> Edit {{$user->name}}</h1>
@stop

@section('content')
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="box box-primary">
            <div class="box-header with-border">
                <a href="{{ url('/admin/users') }}" title="Back"><button class="btn btn-warning btn-xs"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
            </div>
            <div class="box-body">

                {{ Form::model($user, array('route' => array('admin.users.update', $user->id), 'method' => 'PUT')) }}{{-- Form model binding to automatically populate our fields with user data --}}

                <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                    {{ Form::label('name', 'Name') }}
                    {{ Form::text('name', null, array('class' => 'form-control')) }}
                    {!! $errors->first('name','<p class="text-danger"><strong>:message</strong></p>') !!}
                </div>

                <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                    {{ Form::label('email', 'Email') }}
                    {{ Form::email('email', null, array('class' => 'form-control')) }}
                    {!! $errors->first('email','<p class="text-danger"><strong>:message</strong></p>') !!}
                </div>

                <h5><b>Give Role</b></h5>

                <div class='form-group'>
                    @foreach ($roles as $role)
                    {{ Form::checkbox('roles[]',  $role->id, $user->roles ) }}
                    {{ Form::label($role->name, ucfirst($role->name)) }}<br>

                    @endforeach
                </div>

                <div class="form-group {{ $errors->has('password') ? 'has-error' : '' }}">
                    {{ Form::label('password', 'Password') }}<br>
                    {{ Form::password('password', array('class' => 'form-control')) }}
                    {!! $errors->first('password','<p class="text-danger"><strong>:message</strong></p>') !!}
                </div>

                <div class="form-group {{ $errors->has('password_confirmation') ? 'has-error' : '' }}">
                    {{ Form::label('password', 'Confirm Password') }}<br>
                    {{ Form::password('password_confirmation', array('class' => 'form-control')) }}
                    {!! $errors->first('password_confirmation','<p class="text-danger"><strong>:message</strong></p>') !!}
                </div>

                {{ Form::submit('Update', array('class' => 'btn btn-primary')) }}

                {{ Form::close() }}

            </div>
        </div>
    </div>
</div>
@stop

resources/views/admin/users/index.blade.php
@extends('adminlte::page')

@section('title', 'Admin Users')

@section('content_header')
<h1><i class="fa fa-users"></i> Admin Users</h1>
@stop

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="box box-success">
            <div class="box-header">
                <?php $user = Auth::guard('admin')->user(); ?>
                @if($user->hasRole('super-admin','admin') || $user->hasPermissionTo('role_read','admin'))
                <a href="{{ route('admin.roles.index') }}" class="btn btn-default btn-sm">Roles</a>
                @endif
                @if($user->hasRole('super-admin','admin') || $user->hasPermissionTo('permission_read','admin'))
                <a href="{{ route('admin.permissions.index') }}" class="btn btn-default btn-sm">Permissions</a>
                @endif
                @if($user->hasRole('super-admin','admin') || $user->hasPermissionTo('user_create','admin'))
                <a href="{{ route('admin.users.create') }}" class="btn btn-success btn-sm">Add User</a>
                @endif
            </div>
            <div class="box-body">

                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover" id="users-table">

                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Date/Time Added</th>
                                <th>User Roles</th>
                                <th>Actions</th>
                            </tr>
                        </thead>


                    </table>
                </div>

            </div>
        </div>
    </div>
</div>
@stop
@section('js')
<script src="{{asset('vendor/adminlte/plugins/iCheck/icheck.min.js')}}"></script>
<script type='text/javascript'>
$(function () {
    oTable = $('#users-table').DataTable({
        processing: false,
        serverSide: true,
        ajax: {
            url: '{!! route('admin.users.datatable') !!}',
            type: 'post',
            headers: {'X-CSRF-TOKEN': '{{ csrf_token() }}'}
        },
        columns: [
            {data: 'id', name: 'id'},
            {data: 'name', name: 'name'},
            {data: 'email', name: 'email'},
            {data: 'created_at', name: 'created_at', orderable: false, searchable: false},
            {data: 'roles', name: 'roles', orderable: false, searchable: false},
            {data: 'actions', name: 'actions', orderable: false, searchable: false}
        ]
    });

    $('#users-table').on('click', '.destroy', function (e) {
        e.preventDefault();

        var href = $(this).attr('href');

        bootbox.confirm("{{ trans('myadmin.confirm-delete') }}", function (result) {
            if (result === false)
                return;

            $.ajax({
                url: href,
                method: 'DELETE',
                headers: {'X-CSRF-TOKEN': '{{ csrf_token() }}'},
                success: function () {
                    oTable.ajax.reload();
                    growl("User successfully deleted.", "success");
                }
            });
        });
    });
});
</script>    
@stop

resources/views/admin/users/profile.blade.php
@extends('adminlte::page')

@section('title', 'My Profile')

@section('content_header')
<h1><i class='fa fa-user'></i> My Profile</h1>
@stop

@section('content')
    {{ Form::open(['route' => ['admin.user.profile'], 'method' => 'post', 'autocomplete' => 'off', 'files' => true]) }}
        <div class="row">
            <div class="col-sm-12 mbl">
                <span class="btn-group pull-right">
                    <button type="submit" class="btn btn-primary">Save</button>
                </span>
            </div>
        </div>
    <br style="clear: both;">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-5 col-lg-5">
                <div class="info-box">
                    <span class="info-box-icon" style="line-height: normal">
                        <img src="{{ $user->avatar_url }}" class="avatar" alt="avatar"/>
                    </span>
                    <div class="info-box-content">
                        <span class="info-box-text">
                            <p class="mbn"><strong class="h3">{{ $user->name  }}</strong></p>
                            <p class="">{{ $user->roles()->pluck('name')->implode(' ') }}</p>
                        </span>
                        <span class="info-box-more">
                            <p class="mbn text-muted">
                                {{ trans('myadmin.profile.subscribedsince', [
                                    'date' => $user->created_at->format(trans('date.lFdY')),
                                    'since' => $user->created_at->diffForHumans()]) }}
                            </p>
                        </span>
                    </div>
                </div>
                <div class="box box-info">
                    <div class="box-header">
                        @if(is_file($user->avatar_path))
                        <span class="pull-right">
                            <button class="btn btn-xs btn-default" id="remove_avatar">
                                {{ trans('myadmin.profile.delavatar') }}
                            </button>
                        </span>
                        @endif
                        <h3 class="box-title">{{ trans('myadmin.profile.avatar') }}</h3>
                    </div>
                    <div class="box-body">
                        <div class="form-group {{ $errors->has('avatar') ? 'has-error' : '' }}">
                            {!! Form::file('avatar', ['id' => 'avatar']) !!}
                            {!! $errors->first('avatar','<p class="text-danger"><strong>:message</strong></p>') !!}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-7 col-lg-7">
                <div class="box box-primary">
                    <div class="box-header">
                        <h3 class="box-title">Informations</h3>
                    </div>
                    <div class="box-body">
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                                <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                                    {{ Form::label('name', 'Name') }}
                                    {{ Form::text('name', old('name', $user->name), ['class' => 'form-control', 'autofocus']) }}
                                    {!! $errors->first('name','<p class="text-danger"><strong>:message</strong></p>') !!}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                                <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                                    {{ Form::label('email', 'Email') }}
                                    {{ Form::text('email', old('email', $user->email), ['class' => 'form-control']) }}
                                    {!! $errors->first('email','<p class="text-danger"><strong>:message</strong></p>') !!}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                                <div class="form-group {{ $errors->has('password') ? 'has-error' : '' }}">
                                    {{ Form::label('password', 'Password') }}
                                    {{ Form::password('password', ['class' => 'form-control']) }}
                                    {!! $errors->first('password','<p class="text-danger"><strong>:message</strong></p>') !!}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                                <div class="form-group {{ $errors->has('password_confirmation') ? 'has-error' : '' }}">
                                    {{ Form::label('password_confirmation', 'Confirm Password') }}
                                    {{ Form::password('password_confirmation', ['class' => 'form-control']) }}
                                    {!! $errors->first('password_confirmation','<p class="text-danger"><strong>:message</strong></p>') !!}
                                </div>
                            </div>                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {{ Form::close() }}
@stop

@section('css')
<link rel="stylesheet" href="{!! asset('vendor/adminlte/plugins/bootstrap-fileinput/css/fileinput.min.css') !!}">
@stop

@section('js')
<script src="{!! asset('vendor/adminlte/plugins/bootstrap-fileinput/js/fileinput.min.js') !!}"></script>
<script>
    $('#avatar').fileinput({
        showUpload: false,
        uploadAsync: false
    });

    $('#remove_avatar').on('click', function(e){
        e.preventDefault();

        bootbox.confirm("{{ trans('myadmin.profile.confirmdelavatar') }}", function(e){
            if(e === false) return;

            $.ajax({
                url: '{{ route('admin.user.avatardelete') }}',
                type: 'post',
                headers: {'X-CSRF-TOKEN': '{{ csrf_token() }}'},
                cache: false,
                success: function(res) {
                    $('.avatar').attr('src', "{{ asset('/images/default_user.png') }}");
                    growl("{{ trans('myadmin.profile.successdelavatar') }}", "success");
                    $('#remove_avatar').remove();
                }
            });
        })
    });

</script>
@stop